site_name: BhashaX docs
site_url: https://example.com/
nav:
    - Home: index.md
    - Basic:
      - About us: /en/about.md
    - English:
        - Documentation: en.md


theme: 
  name: material
  logo: https://github.com/krishyadav007/BhashaX/raw/main/Logo/Logo.png?raw=true
  favicon: images/favicon.png
  palette: 
  - scheme: default
    toggle:
      icon: material/weather-sunny 
      name: Switch to dark mode
  - scheme: slate 
    toggle:
      icon: material/weather-night
      name: Switch to light mode